[[query-operators]]
Operators
=========

[[query-operators-summary]]
== Operators at a glance ==

|===
| <<query-operators-mathematical,Mathematical operators>> | `+`, `-`, `*`, `/`, `%`, `^`
| <<query-operators-comparison,Comparison operators>>     | `=`, `<>`, `<`, `>`, `<=`, `>=`, `IS NULL`, `IS NOT NULL`
| <<query-operators-comparison,String-specific comparison operators>> | `STARTS WITH`, `ENDS WITH`, `CONTAINS`
| <<query-operators-boolean,Boolean operators>> | `AND`, `OR`, `XOR`, `NOT`
| <<query-operators-string,String operators>>   | `+` for concatenation, `=~` for regex matching
| <<query-operators-list,List operators>>       | `+` for concatenation, `IN` to check existence of an element in a list
|===

[[query-operators-mathematical]]
== Mathematical operators ==

The mathematical operators include `+`, `-`, `*`, `/`, `%`, and `^`.

[[query-operators-comparison]]
== Comparison operators ==

The comparison operators include `=`, `<>`, `<`, `>`, `\<=`, `>=`, `IS NULL`, and `IS NOT NULL`.
See <<cypher-comparison>> on their behavior.

The operators `STARTS WITH`, `ENDS WITH` and `CONTAINS` can be used to search for a string value by its content.

[[query-operators-boolean]]
== Boolean operators ==
The boolean operators are `AND`, `OR`, `XOR`, and `NOT`.

[[query-operators-string]]
== String operators ==

Strings can be concatenated using the `+` operator.
For regular expression matching the `=~` operator is used.

[[query-operators-list]]
== List operators ==

Lists can be concatenated using the `+` operator.
The `IN` operator can be used to check if an element exists in a list.

[[query-operators-property]]
== Property operators ==

[NOTE]
Since version 2.0, the previously supported property operators `?` and `!` have been removed.
This syntax is no longer supported.
Missing properties are now returned as `null`.
Please use `(NOT(has(<ident>.prop)) OR <ident>.prop=<value>)` if you really need the old behavior of the `?` operator.
-- Also, the use of `?` for optional relationships has been removed in favor of the newly-introduced `OPTIONAL MATCH` clause.

