[[administration]]
= Administration

[abstract]
--
This chapter explains how to use Cypher to administer Neo4j databases, for the purpose of managing security.
--

Neo4j supports the management of multiple databases within the same DBMS.
The metadata for these databases, including the associated security model, is maintained in a special database called the `system` database.
Most administrative commands must be executed against the `system` database because they involve editing the metadata for the entire system.
This includes all commands related to defining and managing the security model: users, roles and privileges.
The administrative commands that are specific to the schema of an individual database are still executed against that specific database.

* <<administration-security, Security>>
** <<administration-security-introduction, Introduction>>
** <<administration-security-syntax-rules, Syntax summaries>>
** <<administration-security-users-and-roles, User and role management>>
** <<administration-security-subgraph, Graph and sub-graph access control>>
** <<administration-security-reads, Read privileges>>
** <<administration-security-writes, Write privileges>>
** <<administration-security-administration, Security of administration>>
** <<administration-built-in-roles, Built-in roles>>
** <<administration-security-limitations, Known limitations of security>>

include::ql/administration/security/index.asciidoc[leveloffset=+1]
