[[query-use]]
= USE

[abstract]
--
The `USE` clause determines which graph a query, or query part, is executed against.
--

* <<query-use-introduction, Introduction>>
* <<query-use-syntax, Syntax>>
** <<query-use-syntax-composite, Composite database syntax>>
* <<query-use-examples, Examples>>
** <<query-use-examples-query-graph, Query a graph>>
** <<query-use-examples-query-composite-database-constituent-graph, Query a composite database constituent graph>>
** <<query-use-examples-query-composite-database-constituent-graph-dynamically, Query a composite database constituent graph dynamically>>

[[query-use-introduction]]
== Introduction

The `USE` clause determines which graph a query, or query part, is executed against.
It is supported for queries and schema commands.

[[query-use-syntax]]
== Syntax

The `USE` clause can only appear as the prefix of schema commands, or as the first clause of queries:

[source, cypher, role=noplay]
----
USE <graph>
<other clauses>
----

Where `<graph>` refers to the name or alias of a database in the DBMS.


[[query-use-syntax-composite]]
=== Composite database syntax

When running queries against a <<composite-databases, composite database>>, the `USE` clause can also appear as the first clause of:

* Union parts:
+
[source, cypher, role=noplay]
----
USE <graph>
<other clauses>
  UNION
USE <graph>
<other clauses>
----

* Subqueries:
+
[source, cypher, role=noplay]
----
CALL {
  USE <graph>
  <other clauses>
}
----
+
In subqueries, a `USE` clause may appear as the second clause, if directly following an <<subquery-correlated-importing, importing `WITH` clause>>

When executing queries against a composite database, the `USE` clause must only refer to graphs that are constituents of the current composite database.


[[query-use-examples]]
== Examples


[[query-use-examples-query-graph]]
=== Query a graph

In this example it is assumed that the DBMS contains a database named `myDatabase`:

.Query.
[source, cypher]
----
USE myDatabase
MATCH (n) RETURN n
----


[[query-use-examples-query-composite-database-constituent-graph]]
=== Query a composite database constituent graph

In this example it is assumed that the DBMS contains a composite database named `myComposite`, containing an alias named `myConstituent`:

.Query.
[source, cypher]
----
USE myComposite.myConstituent
MATCH (n) RETURN n
----


[[query-use-examples-query-composite-database-constituent-graph-dynamically]]
=== Query a composite database constituent graph dynamically

The built-in function `graph.byName()` can be used in the `USE` clause to resolve a constituent graph from a string value containing the qualified name of a constituent.

This examples assumes the same setup as the previous one: a composite database named `myComposite`, containing an alias named `myConstituent`:

.Query.
[source, cypher]
----
USE graph.byName('myComposite.myConstituent')
MATCH (n) RETURN n
----

The argument can be any expression that evaluates to the name of a constituent graph - for example a parameter:

.Query.
[source, cypher]
----
USE graph.byName($graphName)
MATCH (n) RETURN n
----