[[query-tuning-indexes]]
= The use of indexes

[abstract]
--
This section describes the query plans when indexes are used in various scenarios.
--

The task of tuning calls for different indexes depends on what the queries look like.
Therefore, it is important to have a fundamental understanding of how the indexes operate.
This section describes the query plans that result from different index scenarios.

[NOTE]
====
Node indexes and relationship indexes operate in the same way.
Therefore, node and relationship indexes are used interchangeably in this section.
====

For instructions on how to create and maintain indexes, refer to <<administration-indexes-search-performance>>.

== Index types and predicate compatibility

Generally, an index solves some combination of a label/relationship type predicate and property predicates at the same time.
There are different types of indexes available in Neo4j and these are compatible with different property predicates.

Indexes are most often used for `MATCH` and `OPTIONAL MATCH` clauses that combine a label/relationship type predicate with a property predicate.
Therefore, it is important to know what kind of predicates can be solved by the different indexes.

=== TOKEN LOOKUP indexes

`TOKEN LOOKUP` indexes are present by default and solve only label and relationship type predicates:

[options="header"]
|===
|Label and relationship type predicates
|`MATCH (n:Label)`
|`MATCH (n) WHERE n:Label`
|`MATCH ()-[r:REL]\->()`
|`MATCH ()-[r]->() WHERE r:REL`
|===

[WARNING]
====
`TOKEN LOOKUP` are the most important indexes in the database because they improve the performance of the Cypher queries and the population of other indexes.
Dropping these indexes may lead to severe performance degradation.
Therefore, carefully consider the consequences before doing so.
====

=== RANGE indexes

In combination with label and relationship type predicates, `RANGE` indexes support most types of predicates:

[options="header"]
|===
|Predicate | Syntax
|equality check| `n.prop = value`
|list membership check| `n.prop IN list`
|existence check| `n.prop IS NOT NULL`
|range search| `n.prop > value`
|prefix search| `STARTS WITH`
|===

=== POINT indexes

`POINT` indexes only work for predicates operating on points.
Therefore, `POINT` indexes are only used when it is known that the predicate evaluates to `null` for all non-point values.

`POINT` indexes only support point type predicates:

[options="header"]
|===
|Predicate | Syntax
|property point value| `n.prop = point({x:value, y:value})`
|within bounding box| `point.withinBBox(n.prop, lowerLeftCorner, upperRightCorner)`
|distance| `point.distance(n.prop, center) < = distance`
|===

=== TEXT indexes

In combination with label and relationship type predicates, `TEXT` indexes only solve predicates operating on strings.
That means that `TEXT` indexes are only used when it is known that the predicate evaluates to `null` for all non-string values.

Predicates that only operate on strings are always solvable by a `TEXT` index:

* `STARTS WITH`
* `ENDS WITH`
* `CONTAINS`

However, other predicates are only used when it is known that the property is compared to a string:

* `n.prop = "string"`
* `n.prop IN ["a", "b", "c"]`

This means that a `TEXT` index is not able to solve e.g. `a.prop = b.prop`.

In summary, `TEXT` indexes support the following predicates:

[options="header"]
|===
|Predicate | Syntax
|equality check| `n.prop = "string"`
|list membership check | `n.prop IN ["a", "b", "c"]`
|prefix search| `STARTS WITH`
|suffix search| `ENDS WITH`
|substring search| `CONTAINS`
|===

== Index preference

When multiple indexes are available and able to solve a predicate, there is an order defined that decides which index to use.
It is defined as such:

* `TEXT` indexes are used over `RANGE` and `POINT` indexes for `CONTAINS` and `ENDS WITH`.
* `POINT` indexes are used over `RANGE` and `TEXT` indexes for distance and within a bounding box.
* `RANGE` indexes are preferred over `TEXT` and `POINT` indexes in all other cases.

`TOKEN LOOKUP` indexes are not defined in this order since they never solve the same set of predicates as the other indexes.

include::ql/administration/indexes/node-label-lookup-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/relationship-type-lookup-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/relationship-range-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/node-range-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/node-text-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/relationship-range-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/relationship-text-index-example.asciidoc[leveloffset=2]

include::ql/administration/indexes/multiple-available-index-types.asciidoc[leveloffset=2]

include::ql/administration/indexes/equality-check-using-where-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/equality-check-using-where-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/range-comparisons-using-where-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/range-comparisons-using-where-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/multiple-range-comparisons-using-where-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/multiple-range-comparisons-using-where-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/list-membership-check-using-in-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/list-membership-check-using-in-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/prefix-search-using-starts-with-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/prefix-search-using-starts-with-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/suffix-search-using-ends-with-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/suffix-search-using-ends-with-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/substring-search-using-contains-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/substring-search-using-contains-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/existence-check-using-is-not-null-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/existence-check-using-is-not-null-composite-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/spatial-distance-searches-single-property-index.asciidoc[leveloffset=2]

include::ql/administration/indexes/spatial-bounding-box-searches-single-property-index.asciidoc[leveloffset=2]
