[role=fabric]
[[query-use]]
= USE

[abstract]
--
The `USE` clause determines which graph a query, or query part, is executed against.
--

* <<query-use-introduction, Introduction>>
* <<query-use-syntax, Syntax>>
* <<query-use-examples, Examples>>
** <<query-use-examples-query-graph-by-name, Query remote graph by name>>
** <<query-use-examples-query-graph-by-graph-id, Query remote graph by graph ID>>

[[query-use-introduction]]
== Introduction

The `USE` clause determines which graph a query, or query part, is executed against.

[NOTE]
====
This functionality is currently only available in Neo4j Fabric.
Find out more about this feature in <<operations-manual#fabric, Operations Manual -> Fabric>>.
====

[[query-use-syntax]]
== Syntax

The `USE` clause can only appear as the first clause of:

* Queries:
+
[source, cypher]
----
USE <graph>
<other clauses>
----

* Union parts:
+
[source, cypher]
----
USE <graph>
<other clauses>
  UNION
USE <graph>
<other clauses>
----

* Subqueries:
+
[source, cypher]
----
CALL {
  USE <graph>
  <other clauses>
}
----
+
In subqueries, a `USE` clause may appear as the second clause, if directly following an <<subquery-correlated-importing, importing `WITH` clause>>


[[query-use-examples]]
== Examples

In the following examples we assume that we have configured a Fabric database called `exampleFabricSetup`.

[[query-use-examples-query-graph-by-name]]
=== Query graph by name

The graph that we wish to query is configured to be referred to by the name `exampleDatabaseName`.

.Query.
[source, cypher]
----
USE exampleFabricSetup.exampleDatabaseName
----

[[query-use-examples-query-graph-by-graph-id]]
=== Query graph by graph ID

The graph we wish to query is configured with the graph id `0`, which is why we can refer to it
using the built-in function `graph()` with the argument `0`:

.Query.
[source, cypher]
----
USE exampleFabricSetup.graph(0)
----

