[[query-use]]
= USE

[abstract]
--
The `USE` clause determines which graph a query, or query part, is executed against.
--

* <<query-use-introduction, Introduction>>
* <<query-use-syntax, Syntax>>
* <<query-use-examples, Examples>>
** <<query-use-examples-query-graph-by-name, Query remote graph by name>>
** <<query-use-examples-query-graph-by-graph-id, Query remote graph by graph ID>>

[[query-use-introduction]]
== Introduction

The `USE` clause determines which graph a query, or query part, is executed against.
It is supported for queries and schema commands.

[NOTE]
The `USE` clause can not be used together with the <<load-csv-importing-large-amounts-of-data, `PERIODIC COMMIT` clause>>.


[[query-use-syntax]]
== Syntax

The `USE` clause can only appear as the prefix of schema commands, or as the first clause of queries:

[source, cypher]
----
USE <graph>
<other clauses>
----

Where `<graph>` refers to the name of a database in the DBMS.


[role=fabric]
[[query-use-syntax-fabric]]
=== Fabric syntax

When running queries against a Fabric database, the `USE` clause can also appear as the first clause of:

* Union parts:
+
[source, cypher]
----
USE <graph>
<other clauses>
  UNION
USE <graph>
<other clauses>
----

* Subqueries:
+
[source, cypher]
----
CALL {
  USE <graph>
  <other clauses>
}
----
+
In subqueries, a `USE` clause may appear as the second clause, if directly following an <<subquery-correlated-importing, importing `WITH` clause>>

When executing queries against a Fabric database, in addition to referring to databases in the DBMS, the `<graph>` may also refer to a graph mounted through the Fabric configuration.
For more information, see <<operations-manual#fabric, Operations Manual -> Fabric>>.


[[query-use-examples]]
== Examples


[[query-use-examples-query-graph-by-name]]
=== Query a graph by name

In this example we assume that your DBMS contains a database named `myDatabase`:

.Query.
[source, cypher]
----
USE myDatabase
MATCH (n) RETURN n
----


[role=fabric]
[[query-use-examples-query-fabric-graph-by-name]]
=== Query a Fabric graph by name

In this example we assume that we have configured a Fabric database called `exampleFabricSetup`.
The graph that we wish to query is named `exampleDatabaseName`:

.Query.
[source, cypher]
----
USE exampleFabricSetup.exampleDatabaseName
MATCH (n) RETURN n
----


[role=fabric]
[[query-use-examples-query-graph-by-graph-id]]
=== Query a Fabric graph by graph ID

This examples continues with a Fabric database called `exampleFabricSetup`.

The graph we wish to query is configured with the graph id `0`, which is why we can refer to it using the built-in function `graph()` with the argument `0`:

.Query.
[source, cypher]
----
USE exampleFabricSetup.graph(0)
MATCH (n) RETURN n
----
