[[administration-indexes-search-performance]]
= Indexes for search performance

[abstract]
--
This section explains how to manage indexes used for search performance.
--

This section describes how to manage indexes.
For query performance purposes, it is important to also understand how the indexes are used by the Cypher planner.
Refer to <<query-tuning>> for examples and in-depth discussions on how query plans result from different index and query scenarios.
See specifically <<query-tuning-indexes>> for examples of how various index scenarios result in different query plans.

For information on index configuration and limitations, refer to <<operations-manual#index-configuration, Operations Manual -> Index configuration>>.

[[administration-indexes-types]]
== Indexes (types and limitations)

A database index is a redundant copy of some of the data in the database for the purpose of making searches of related data more efficient.
This comes at the cost of additional storage space and slower writes, so deciding what to index and what not to index is an important and often non-trivial task.

Once an index has been created, it will be managed and kept up to date by the DBMS.
Neo4j will automatically pick up and start using the index once it has been created and brought online.

There are multiple index types available:

* Fulltext index.
* Lookup index.
* Point index.
* Range index.
* Text index types.

[NOTE]
====
The B-tree index type has been replaced by more specific index types (Range, Point, and Text).
====
See <<administration-indexes-fulltext-search>> for more information about fulltext indexes.
Token lookup indexes contain nodes with one or more labels or relationship types, without regard for any properties.

Cypher enables the creation of range indexes on one or more properties for all nodes or relationships with a given label or relationship type:

* An index created on a single property for any given label or relationship type is called a _single-property index_.
* An index created on more than one property for any given label or relationship type is called a _composite index_.

Differences in the usage patterns between composite and single-property indexes are described in <<administration-indexes-single-vs-composite-index>>.

Additionally, text and point indexes are a kind of single-property indexes, with the limitation that they only recognize properties with string and point values, respectively.
Nodes or relationships with the indexed label or relationship type where the indexed property is of another value type are not included in the index.

The following is true for indexes:

* Best practice is to give the index a name when it is created.
If the index is not explicitly named, it gets an auto-generated name.
* The index name must be unique among both indexes and constraints.
* Index creation is by default not idempotent, and an error will be thrown if you attempt to create the same index twice.
Using the keyword `IF NOT EXISTS` makes the command idempotent, and no error will be thrown if you attempt to create the same index twice.


[[administration-indexes-syntax]]
=== Syntax

.Syntax for managing indexes
[options="header", width="100%", cols="5a,3, 3a"]
|===
| Command | Description | Comment

| [source, cypher, role=noplay]
----
CREATE [RANGE] INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName_1[,
    n.propertyName_2,
    …
    n.propertyName_n])
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a range index on nodes, either on a single property or composite.

Index provider can be specified using the `OPTIONS` clause.
.8+.^| Best practice is to give the index a name when it is created.
If the index is not explicitly named, it gets an auto-generated name.

The index name must be unique among both indexes and constraints.

The command is optionally idempotent, with the default behavior to throw an error if you attempt to create the same index twice.
With `IF NOT EXISTS`, no error is thrown and nothing happens should an index with the same name or same schema and index type already exist.
It may still throw an error if conflicting constraints exist, such as constraints with the same name or schema and backing index type.

| [source, cypher, role=noplay]
----
CREATE [RANGE] INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r:TYPE_NAME"]"-()
ON (r.propertyName_1[,
    r.propertyName_2,
    …
    r.propertyName_n])
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a range index on relationships, either on a single property or composite.

Index provider can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR (n)
ON EACH labels(n)
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a node label lookup index.

Index provider can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
CREATE LOOKUP INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r"]"-()
ON [EACH] type(r)
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a relationship type lookup index.

Index provider can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
CREATE TEXT INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a text index on nodes where the property has a string value.

Index provider can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
CREATE TEXT INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r:TYPE_NAME"]"-()
ON (r.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a text index on relationships where the property has a string value.

Index provider can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
CREATE POINT INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a point index on nodes where the property has a point value.

Index provider and configuration can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
CREATE POINT INDEX [index_name] [IF NOT EXISTS]
FOR ()-"["r:TYPE_NAME"]"-()
ON (r.propertyName)
[OPTIONS "{" option: value[, ...] "}"]
----
| Create a point index on relationships where the property has a point value.

Index provider and configuration can be specified using the `OPTIONS` clause.

| [source, cypher, role=noplay]
----
DROP INDEX index_name [IF EXISTS]
----
| Drop an index of any index type.
| The command is optionally idempotent, with the default behavior to throw an error if you attempt to drop the same index twice.
With `IF EXISTS`, no error is thrown and nothing happens should the index not exist.

| [source, cypher, role=noplay]
----
SHOW [ALL\|FULLTEXT\|LOOKUP\|POINT\|RANGE\|TEXT] INDEX[ES]
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List indexes in the database, either all or filtered on index type.
| When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

|===

Creating an index requires <<access-control-database-administration-index, the `CREATE INDEX` privilege>>,
while dropping an index requires <<access-control-database-administration-index, the `DROP INDEX` privilege>> and
listing indexes require <<access-control-database-administration-index, the `SHOW INDEX` privilege>>.

<<query-using>> describes how to make the Cypher planner use specific indexes (especially in cases where the planner would not necessarily have used them).


[[administration-indexes-single-vs-composite-index]]
=== Composite index limitations

Like single-property range indexes, composite range indexes support all predicates:

* equality check: `n.prop = value`
* list membership check: `n.prop IN list`
* existence check: `n.prop IS NOT NULL`
* range search: `n.prop > value`
* prefix search: `STARTS WITH`
* suffix search: `ENDS WITH`
* substring search: `CONTAINS`

[NOTE]
====
For details about each operator, see <<query-operators, Operators>>.
====

However, predicates might be planned as existence check and a filter.
For most predicates, this can be avoided by following these restrictions:

* If there is any `equality check` and `list membership check` predicates,
they need to be for the first properties defined by the index.
* There can be up to one `range search` or `prefix search` predicate.
* There can be any number of `existence check` predicates.
* Any predicate after a `range search`, `prefix search` or `existence check` predicate has to be an `existence check` predicate.

However, the `suffix search` and `substring search` predicates are always planned as existence check and a filter and
any predicates following after will therefore also be planned as such.

For example, an index on nodes with `:Label(prop1,prop2,prop3,prop4,prop5,prop6)` and predicates:

[source, cypher, role=noplay]
----
WHERE n.prop1 = 'x' AND n.prop2 = 1 AND n.prop3 > 5 AND n.prop4 < 'e' AND n.prop5 = true AND n.prop6 IS NOT NULL
----

will be planned as:

[source, cypher, role=noplay]
----
WHERE n.prop1 = 'x' AND n.prop2 = 1 AND n.prop3 > 5 AND n.prop4 IS NOT NULL AND n.prop5 IS NOT NULL AND n.prop6 IS NOT NULL
----

with filters on `n.prop4 < 'e'` and `n.prop5 = true`, since `n.prop3` has a `range search` predicate.

And an index on nodes with `:Label(prop1,prop2)` with predicates:

[source, cypher, role=noplay]
----
WHERE n.prop1 ENDS WITH 'x' AND n.prop2 = false
----

will be planned as:

[source, cypher, role=noplay]
----
WHERE n.prop1 IS NOT NULL AND n.prop2 IS NOT NULL
----

with filters on `n.prop1 ENDS WITH 'x'` and `n.prop2 = false`, since `n.prop1` has a `suffix search` predicate.

Composite indexes require predicates on all properties indexed.
If there are predicates on only a subset of the indexed properties, it will not be possible to use the composite index.
To get this kind of fallback behavior, it is necessary to create additional indexes on the relevant sub-set of properties or on single properties.


[[administration-indexes-examples]]
== Creating indexes

include::../indexes/create-a-single-property-range-index-for-nodes.asciidoc[leveloffset=+1]

include::../indexes/create-a-single-property-range-index-for-relationships.asciidoc[leveloffset=+1]

include::../indexes/create-a-range-index-only-if-it-does-not-already-exist.asciidoc[leveloffset=+1]

include::../indexes/create-a-range-index-specifying-the-index-provider.asciidoc[leveloffset=+1]

include::../indexes/create-a-composite-range-index-for-nodes.asciidoc[leveloffset=+1]

include::../indexes/create-a-composite-range-index-for-relationships.asciidoc[leveloffset=+1]

include::../indexes/create-a-node-label-lookup-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-relationship-type-lookup-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-token-lookup-index-specifying-the-index-provider.asciidoc[leveloffset=+1]

include::../indexes/create-a-node-text-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-relationship-text-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-text-index-only-if-it-does-not-already-exist.asciidoc[leveloffset=+1]

include::../indexes/create-a-text-index-specifying-the-index-provider.asciidoc[leveloffset=+1]

include::../indexes/create-a-node-point-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-relationship-point-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-point-index-only-if-it-does-not-already-exist.asciidoc[leveloffset=+1]

include::../indexes/create-a-point-index-specifying-the-index-provider.asciidoc[leveloffset=+1]

include::../indexes/create-a-point-index-specifying-the-index-configuration.asciidoc[leveloffset=+1]

include::../indexes/create-a-point-index-specifying-both-the-index-provider-and-configuration.asciidoc[leveloffset=+1]

include::../indexes/failure-to-create-an-already-existing-index.asciidoc[leveloffset=+1]

include::../indexes/failure-to-create-an-index-with-the-same-name-as-an-already-existing-index.asciidoc[leveloffset=+1]

include::../indexes/failure-to-create-an-index-when-a-constraint-already-exists.asciidoc[leveloffset=+1]

include::../indexes/failure-to-create-an-index-with-the-same-name-as-an-already-existing-constraint.asciidoc[leveloffset=+1]


[[administration-indexes-list-indexes]]
== Listing indexes

Listing indexes can be done with `SHOW INDEXES`, which will produce a table with the following columns:

.List indexes output
[options="header", width="100%", cols="1a,4,^.^,^"]
|===
| Column
| Description
| Default output
| Full output

| `id`
| The id of the index.
| `+`
| `+`

| `name`
| Name of the index (explicitly set by the user or automatically assigned).
| `+`
| `+`

| `state`
| Current state of the index.
| `+`
| `+`

| `populationPercent`
| % of index population.
| `+`
| `+`

| `type`
| The IndexType of this index (`FULLTEXT`, `LOOKUP`, `POINT`, `RANGE`, or `TEXT`).
| `+`
| `+`

| `entityType`
| Type of entities this index represents (nodes or relationship).
| `+`
| `+`

| `labelsOrTypes`
| The labels or relationship types of this index.
| `+`
| `+`

| `properties`
| The properties of this index.
| `+`
| `+`

| `indexProvider`
| The index provider for this index.
| `+`
| `+`

| `owningConstraint`
| The name of the constraint the index is associated with or `null`, in case it is not associated with any constraint.
| `+`
| `+`

| `options`
| The options passed to `CREATE` command.
|
| `+`

| `failureMessage`
| The failure description of a failed index.
|
| `+`

| `createStatement`
| Statement used to create the index.
|
| `+`
|===

Listing indexes also allows for `WHERE` and `YIELD` clauses to filter the returned rows and columns.

[NOTE]
====
While the command for listing indexes require  the <<access-control-database-administration-index, `SHOW INDEX` privilege>>,
the deprecated built-in procedures for listing indexes, such as `db.indexes`, work as before and are not affected by the privilege.
====


=== Listing indexes examples

//cypher/cypher-docs/target/docs/dev/ql/administration/indexes/listing-all-indexes.asciidoc
include::../indexes/listing-all-indexes.asciidoc[leveloffset=+2]

//cypher/cypher-docs/target/docs/dev/ql/administration/indexes/listing-indexes-with-filtering.asciidoc
include::../indexes/listing-indexes-with-filtering.asciidoc[leveloffset=+2]


[[administration-indexes-drop-indexes]]
== Deleting indexes

include::../indexes/drop-an-index.asciidoc[leveloffset=+1]

include::../indexes/drop-a-non-existing-index.asciidoc[leveloffset=+1]
