[[administration-indexes-search-performance]]
= Indexes for search performance

[abstract]
--
This section explains how to manage indexes used for search performance.
--

* <<administration-indexes-introduction, Introduction>>
* <<administration-indexes-syntax, Syntax>>
* <<administration-indexes-single-vs-composite-index, Composite index limitations>>
* <<administration-indexes-examples, Examples>>
** <<administration-indexes-create-a-single-property-index, Create a single-property index>>
** <<administration-indexes-create-a-single-property-index-only-if-it-does-not-already-exist, Create a single-property index only if it does not already exist>>
** <<administration-indexes-create-a-composite-index, Create a composite index>>
** <<administration-indexes-replace-a-composite-index, Replace a composite index>>
** <<administration-indexes-drop-an-index, Drop an index>>
** <<administration-indexes-drop-a-non-existing-index, Drop a non-existing index>>
** <<administration-indexes-list-indexes, List indexes>>
** <<administration-indexes-examples-deprecated-syntax, Deprecated syntax>>

This section describes how to manage indexes.
For query performance purposes, it is important to also understand how the indexes are used by the Cypher planner.
Refer to <<query-tuning>> for examples and in-depth discussions on how query plans result from different index and query scenarios.
See specifically <<query-tuning-indexes>> for examples of how various index scenarios result in different query plans.

For information on index configuration and limitations, refer to <<operations-manual#index-configuration, Operations Manual -> Index configuration>>.


[[administration-indexes-introduction]]
== Introduction

A database index is a redundant copy of some of the data in the database for the purpose of making searches of related data more efficient.
This comes at the cost of additional storage space and slower writes, so deciding what to index and what not to index is an important and often non-trivial task.

Once an index has been created, it will be managed and kept up to date by the DBMS.
Neo4j will automatically pick up and start using the index once it has been created and brought online.

Cypher enables the creation of indexes on one or more properties for all nodes that have a given label:

* An index that is created on a single property for any given label is called a _single-property index_.
* An index that is created on more than one property for any given label is called a _composite index_.

Differences in the usage patterns between composite and single-property indexes are described in <<administration-indexes-single-vs-composite-index>>.

The following is true for indexes: 

* Best practice is to give the index a name when it is created.
If the index is not explicitly named, it will get an auto-generated name.
* The index name must be unique among both indexes and constraints.
* Index creation is by default not idempotent, and an error will be thrown if you attempt to create the same index twice.
Using the keyword `IF NOT EXISTS` makes the command idempotent, and no error will be thrown if you attempt to create the same index twice.


[[administration-indexes-syntax]]
== Syntax

.Syntax for managing indexes
[options="header", width="100%", cols="5a,3, 3a"]
|===
| Command | Description | Comment

| [source, cypher]
----
CREATE INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName)
----
| Create a single-property index.
.2+.^| Best practice is to give the index a name when it is created.
If the index is not explicitly named, it will get an auto-generated name.

The index name must be unique among both indexes and constraints.

The command is optionally idempotent, with the default behavior to throw an error if you attempt to create the same index twice.
With `IF NOT EXISTS`, no error is thrown and nothing happens should an index with the same name, schema or both already exist.
It may still throw an error should a conflicting constraint exist.

| [source, cypher]
----
CREATE INDEX [index_name] [IF NOT EXISTS]
FOR (n:LabelName)
ON (n.propertyName_1,
    n.propertyName_2,
    …
    n.propertyName_n)
----
| Create a composite index.

| [source, cypher]
----
DROP INDEX index_name [IF EXISTS]
----
| Drop an index
| The command is optionally idempotent, with the default behavior to throw an error if you attempt to drop the same index twice.
With `IF EXISTS`, no error is thrown and nothing happens should the index not exist.

| [source, cypher]
----
CALL db.indexes
----
| List all indexes in the database. 
| 

| [source, cypher]
----
DROP INDEX ON :LabelName(propertyName)
----
| Drop a single-property index without specifying a name.
.2+.^| [deprecated]#This syntax is deprecated.#

| [source, cypher]
----
DROP INDEX ON :LabelName (n.propertyName_1,
n.propertyName_2,
…
n.propertyName_n)
----
| Drop a composite index without specifying a name. 
|===

<<query-using>> describes how to make the Cypher planner use specific indexes (especially in cases where the planner would not necessarily have used them).


[[administration-indexes-single-vs-composite-index]]
== Composite index limitations

Like single-property indexes, composite indexes support all predicates:

* equality check: `n.prop = value`
* list membership check: `n.prop IN list`
* existence check: `exists(n.prop)`
* range search: `n.prop > value`
* prefix search: `STARTS WITH`
* suffix search: `ENDS WITH`
* substring search: `CONTAINS`

However, predicates might be planned as existence check and a filter.
For most predicates, this can be avoided by following these restrictions:

* If there is any `equality check` and `list membership check` predicates,
they need to be for the first properties defined by the index.
* There can be up to one `range search` or `prefix search` predicate.
* There can be any number of `existence check` predicates.
* Any predicate after a `range search`, `prefix search` or `existence check` predicate has to be an `existence check` predicate.

However, the `suffix search` and `substring search` predicates are always planned as existence check and a filter and
any predicates following after will therefore also be planned as such.

For example, an index on `:Label(prop1,prop2,prop3,prop4,prop5,prop6)` and predicates:

```
WHERE n.prop1 = 'x' AND n.prop2 = 1 AND n.prop3 > 5 AND n.prop4 < 'e' AND n.prop5 = true AND exists(n.prop6)
```

will be planned as:

```
WHERE n.prop1 = 'x' AND n.prop2 = 1 AND n.prop3 > 5 AND exists(n.prop4) AND exists(n.prop5) AND exists(n.prop6)
```

with filters on `n.prop4 < 'e'` and `n.prop5 = true`, since `n.prop3` has a `range search` predicate.

And an index on `:Label(prop1,prop2)` with predicates:

```
WHERE n.prop1 ENDS WITH 'x' AND n.prop2 = false
```

will be planned as:

```
WHERE exists(n.prop1) AND exists(n.prop2)
```

with filters on `n.prop1 ENDS WITH 'x'` and `n.prop2 = false`, since `n.prop1` has a `suffix search` predicate.

Composite indexes require predicates on all properties indexed.
If there are predicates on only a subset of the indexed properties, it will not be possible to use the composite index.
To get this kind of fallback behavior, it is necessary to create additional indexes on the relevant sub-set of properties or on single properties.


[[administration-indexes-examples]]
== Examples

include::../indexes/create-a-single-property-index.asciidoc[leveloffset=+1]

include::../indexes/create-a-single-property-index-only-if-it-does-not-already-exist.asciidoc[leveloffset=+1]

include::../indexes/create-a-composite-index.asciidoc[leveloffset=+1]

include::../indexes/drop-an-index.asciidoc[leveloffset=+1]

include::../indexes/drop-a-non-existing-index.asciidoc[leveloffset=+1]

include::../indexes/list-indexes.asciidoc[leveloffset=+1]

[role=deprecated]
[[administration-indexes-examples-deprecated-syntax]]
=== Deprecated syntax

include::../indexes/drop-a-single-property-index.asciidoc[leveloffset=+2]

include::../indexes/drop-a-composite-index.asciidoc[leveloffset=+2]
