[[cypher-introduction]]
= What is Cypher?

Cypher is a declarative graph query language that allows for expressive and efficient <<cypher-querying-updating-administering, querying, updating and administering>> of the graph.
It is designed to be suitable for both developers and operations professionals.
Cypher is designed to be simple, yet powerful; highly complicated database queries can be easily expressed, enabling you to focus on your domain, instead of getting lost in database access.

Cypher is inspired by a number of different approaches and builds on established practices for expressive querying.
Many of the keywords, such as `WHERE` and `ORDER BY`, are inspired by http://en.wikipedia.org/wiki/SQL[SQL].
Pattern matching borrows expression approaches from http://en.wikipedia.org/wiki/SPARQL[SPARQL].
Some of the list semantics are borrowed from languages such as Haskell and Python.
Cypher's constructs, based on English prose and neat iconography, make queries easy, both to write and to read.

NOTE
====
Names are case-sensitive.
`:PERSON`, `:Person` and `:person` are three different labels, as well as `n` and `N` are two different variables.
====

**Structure**

Cypher borrows its structure from SQL -- queries are built up using various clauses.

Clauses are chained together, and they feed intermediate result sets between each other.
For example, the matching variables from one `MATCH` clause will be the context that the next clause exists in.

The query language is comprised of several distinct clauses.
These are discussed in more detail in the chapter on <<query-clause, Clauses>>.

The following are a few examples of clauses used to read from the graph:

* `MATCH`: The graph pattern to match.
  This is the most common way to get data from the graph.

* `WHERE`: Not a clause in its own right, but rather part of `MATCH`, `OPTIONAL MATCH` and `WITH`.
  Adds constraints to a pattern, or filters the intermediate result passing through `WITH`.

* `RETURN`: What to return.

Let's see `MATCH` and `RETURN` in action.

include::intro-examples.asciidoc[]

And these are examples of clauses that are used to update the graph:

* `CREATE` (and `DELETE`): Create (and delete) nodes and relationships.

* `SET` (and `REMOVE`): Set values to properties and add labels on nodes using `SET` and use `REMOVE` to remove them.

* `MERGE`: Match existing or create new nodes and patterns. This is especially useful together with unique constraints.
