The syntax of the database management commands is as follows:

.Database management command syntax
[options="header", width="100%", cols="1,5a"]
|===
| Command | Syntax
| Show Database
| [source]
SHOW { DATABASE name \| DATABASES \| DEFAULT DATABASE \| HOME DATABASE }
[WHERE expression]

[source]
SHOW { DATABASE name \| DATABASES \| DEFAULT DATABASE \| HOME DATABASE }
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
| Create Database
| [source]
CREATE DATABASE name [IF NOT EXISTS]
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]

[source]
CREATE OR REPLACE DATABASE name
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
| Create Composite Database
| [source]
CREATE COMPOSITE DATABASE name [IF NOT EXISTS]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]

[source]
CREATE OR REPLACE COMPOSITE DATABASE name
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Alter Database
| [source]
ALTER DATABASE name [IF EXISTS]
{
SET ACCESS {READ ONLY \| READ WRITE} \|
SET TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]
}
|Stop Database
| [source]
STOP DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Start Database
| [source]
START DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Drop Database
| [source]
DROP [COMPOSITE] DATABASE name [IF EXISTS] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|===

