The syntax of the database management commands is as follows:

.Database management command syntax
[options="header", width="100%", cols="1,5a"]
|===
| Command | Syntax
| Show Database
| [source]
SHOW { DATABASE name \| DATABASES \| DEFAULT DATABASE \| HOME DATABASE }
[WHERE expression]

[source]
SHOW { DATABASE name \| DATABASES \| DEFAULT DATABASE \| HOME DATABASE }
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
| Create Database
| [source]
CREATE DATABASE name [IF NOT EXISTS]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]

[source]
CREATE OR REPLACE DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Alter Database
| [source]
ALTER DATABASE name [IF EXISTS] SET ACCESS {READ ONLY \| READ WRITE}
|Stop Database
| [source]
STOP DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Start Database
| [source]
START DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
|Drop Database
| [source]
DROP DATABASE name [IF EXISTS] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
| Create Alias
| [source]
CREATE [OR REPLACE] ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
| Alter Alias
| [source]
ALTER ALIAS name [IF EXISTS] SET DATABASE TARGET targetName
| Drop Alias
| [source]
DROP ALIAS name [IF EXISTS] FOR DATABASE
|===

