.Role management command syntax
[options="header", width="100%", cols="3a,2,2"]
|===
| Command | Description | Required privilege

| [source, cypher, role=noplay]
----
SHOW [ALL\|POPULATED] ROLES
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List roles.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.
| <<access-control-dbms-administration-role-management, SHOW ROLE>>

| [source, cypher, role=noplay]
----
SHOW [ALL\|POPULATED] ROLES WITH USERS
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List roles and users assigned to them.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.
| <<access-control-dbms-administration-role-management, SHOW ROLE>> and
<<access-control-dbms-administration-user-management, SHOW USER>>

| [source, cypher, role=noplay]
----
SHOW ROLE[S] name[, ...] PRIVILEGE[S] [AS [REVOKE] COMMAND[S]]
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List the privileges granted to the specified roles.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.
| <<access-control-dbms-administration-role-management, SHOW ROLE PRIVILEGES>>

| [source, cypher, role=noplay]
----
CREATE ROLE name [IF NOT EXISTS] [AS COPY OF otherName]
----
| Create a new role.
| <<access-control-dbms-administration-role-management, CREATE ROLE>>

| [source, cypher, role=noplay]
----
CREATE OR REPLACE ROLE name [AS COPY OF otherName]
----
| Create a new role, or if a role with the same name exists, replace it.
| <<access-control-dbms-administration-role-management, CREATE ROLE>> and
<<access-control-dbms-administration-role-management, DROP ROLE>>

| [source, cypher, role=noplay]
----
RENAME ROLE name [IF EXISTS] TO otherName
----
| Change the name of a role.
| <<access-control-dbms-administration-role-management, RENAME ROLE>>

| [source, cypher, role=noplay]
----
DROP ROLE name [IF EXISTS]
----
| Remove a role.
| <<access-control-dbms-administration-role-management, DROP ROLE>>

| [source, cypher, role=noplay]
----
GRANT ROLE name[, ...] TO user[, ...]
----
| Assign roles to users.
| <<access-control-dbms-administration-role-management, ASSIGN ROLE>>

| [source, cypher, role=noplay]
----
REVOKE ROLE name[, ...] FROM user[, ...]
----
| Remove roles from users.
| <<access-control-dbms-administration-role-management, REMOVE ROLE>>
|===
