.User management command syntax
[options="header", width="100%", cols="7a,3,2"]
|===
| Command | Description | Required privilege

| [source, cypher, role=noplay]
----
SHOW CURRENT USER
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List the current user.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.
| None

| [source, cypher, role=noplay]
----
SHOW USERS
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List all users.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.
| <<access-control-dbms-administration-user-management, SHOW USER>>

| [source, cypher, role=noplay]
----
SHOW USER[S] [name[, ...]] PRIVILEGE[S] [AS [REVOKE] COMMAND[S]]
    [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
    [WHERE expression]
    [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
| List the privileges granted to the specified users or the current user, if no user is specified.

When using the `RETURN` clause, the `YIELD` clause is mandatory and may not be omitted.
| <<access-control-dbms-administration-privilege-management, SHOW PRIVILEGE>> and
<<access-control-dbms-administration-user-management, SHOW USER>>

| [source, cypher, role=noplay]
----
CREATE USER name [IF NOT EXISTS]
  SET [PLAINTEXT \| ENCRYPTED] PASSWORD password
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED}]
  [SET HOME DATABASE name]
----
| Create a new user.
| <<access-control-dbms-administration-user-management, CREATE USER>>

| [source, cypher, role=noplay]
----
CREATE OR REPLACE USER name
  SET [PLAINTEXT \| ENCRYPTED] PASSWORD password
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED}]
  [SET HOME DATABASE name]
----
| Create a new user, or if a user with the same name exists, replace it.
| <<access-control-dbms-administration-user-management, CREATE USER>> and
<<access-control-dbms-administration-user-management, DROP USER>>

| [source, cypher, role=noplay]
----
RENAME USER name [IF EXISTS] TO otherName
----
| Change the name of a user.
| <<access-control-dbms-administration-user-management, RENAME USER>>

| [source, cypher, role=noplay]
----
ALTER USER name [IF EXISTS]
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD password]
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED} ]
  [SET HOME DATABASE name]
  [REMOVE HOME DATABASE]
----
| Modify the settings for an existing user. At least one `SET` or `REMOVE` clause is required. `SET` and `REMOVE` clauses cannot be combined in the same command.
| <<access-control-dbms-administration-user-management, SET PASSWORD>>,
<<access-control-dbms-administration-user-management, SET USER STATUS>> and/or
<<access-control-dbms-administration-user-management, SET USER HOME DATABASE>>

| [source, cypher, role=noplay]
----
ALTER CURRENT USER SET PASSWORD FROM original TO password
----
| Change the current user's password.
| None

|
[source, cypher, role=noplay]
----
DROP USER name [IF EXISTS]
----
| Remove an existing user.
| <<access-control-dbms-administration-user-management, DROP USER>>
| `+`
| `+`
|===
[NOTE]
====
[enterprise-edition]#The `SHOW USER[S] PRIVILEGES` command is an enterprise feature.#
====
