[[query-load-csv]]
= LOAD CSV

[abstract]
--
`LOAD CSV` is used to import data from CSV files.
--

* <<query-load-csv-introduction, Introduction>>
* <<csv-file-format, CSV file format>>
* <<load-csv-import-data-from-a-csv-file, Import data from a CSV file>>
* <<load-csv-import-data-from-a-remote-csv-file, Import data from a remote CSV file>>
* <<load-csv-import-data-from-a-csv-file-containing-headers, Import data from a CSV file containing headers>>
* <<load-csv-import-data-from-a-csv-file-with-a-custom-field-delimiter, Import data from a CSV file with a custom field delimiter>>
* <<load-csv-importing-large-amounts-of-data, Importing large amounts of data>>
* <<load-csv-setting-the-rate-of-call-in-transactions, Setting the rate of CALL {} IN TRANSACTIONS>>
* <<load-csv-import-data-containing-escaped-characters, Import data containing escaped characters>>
* <<load-csv-using-linenumber-with-load-csv, Using linenumber() with LOAD CSV>>
* <<load-csv-using-file-with-load-csv, Using file() with LOAD CSV>>


[[query-load-csv-introduction]]
== Introduction

* The URL of the CSV file is specified by using `FROM` followed by an arbitrary expression evaluating to the URL in question.
* It is required to specify a variable for the CSV data using `AS`.
* CSV files can be stored on the database server and are then accessible using a `+file:///+` URL.
  Alternatively, `LOAD CSV` also supports accessing CSV files via _HTTPS_, _HTTP_, and _FTP_.
* `LOAD CSV` supports resources compressed with _gzip_ and _Deflate_. Additionally `LOAD CSV` supports locally stored CSV files compressed with _ZIP_.
* `LOAD CSV` will follow _HTTP_ redirects but for security reasons it will not follow redirects that changes the protocol, for example if the redirect is going from _HTTPS_ to _HTTP_.
* `LOAD CSV` is often used in conjunction with the query clause `CALL +++{ ... }+++ TRANSACTIONS`. More information on this may be found in <<subquery-call-in-transactions, CALL +++{ ... }+++ IN TRANSACTIONS>>.

.Configuration settings for file URLs
<<operations-manual#config_dbms.security.allow_csv_import_from_file_urls, dbms.security.allow_csv_import_from_file_urls>>::
This setting determines if Cypher will allow the use of `+file:///+` URLs when loading data using `LOAD CSV`.
Such URLs identify files on the filesystem of the database server.
Default is _true_.
Setting `dbms.security.allow_csv_import_from_file_urls=false` will completely disable access to the file system for `LOAD CSV`.

<<operations-manual#config_dbms.directories.import, dbms.directories.import>>::
Sets the root directory for `+file:///+` URLs used with the Cypher `LOAD CSV` clause.
This should be set to a single directory relative to the Neo4j installation path on the database server.
All requests to load from `+file:///+` URLs will then be relative to the specified directory.
The default value set in the config settings is _import_.
This is a security measure which prevents the database from accessing files outside the standard <<operations-manual#file-locations, import directory>>,
similar to how a Unix `chroot` operates.
Setting this to an empty field will allow access to all files within the Neo4j installation folder.
Commenting out this setting will disable the security feature, allowing all files in the local system to be imported.
This is definitely not recommended.

File URLs will be resolved relative to the `dbms.directories.import` directory.
For example, a file URL will typically look like `+file:///myfile.csv+` or `+file:///myproject/myfile.csv+`.

* When using `+file:///+` URLs, spaces and other non-alphanumeric characters need to be URL encoded. footnote:[See https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding].
*  If `dbms.directories.import` is set to the default value _import_, using the above URLs in `LOAD CSV` would read from _<NEO4J_HOME>/import/myfile.csv_ and _<NEO4J_HOME>/import/myproject/myfile.csv_ respectively.
*  If it is set to _/data/csv_, using the above URLs in `LOAD CSV` would read from _<NEO4J_HOME>/data/csv/myfile.csv_ and _<NEO4J_HOME>/data/csv/myproject/myfile.csv_ respectively.

[NOTE]
====
The file location is relative to the import.
The config setting `dbms.directories.import` only applies to local disc and **not** to remote URLs.
====

See the examples below for further details.

[[csv-file-format]]
== CSV file format

The CSV file to use with `LOAD CSV` must have the following characteristics:

* the character encoding is UTF-8;
* the end line termination is system dependent, e.g., it is `\n` on unix or `\r\n` on windows;
* the default field terminator is `,`;
* the field terminator character can be change by using the option `FIELDTERMINATOR` available in the `LOAD CSV` command;
* quoted strings are allowed in the CSV file and the quotes are dropped when reading the data;
* the character for string quotation is double quote `"`;
* if `dbms.import.csv.legacy_quote_escaping` is set to the default value of `true`, `\` is used as an escape character;
* a double quote must be in a quoted string and escaped, either with the escape character or a second double quote.

include::import-data-from-a-csv-file.asciidoc[]

include::import-data-from-a-remote-csv-file.asciidoc[]

include::import-data-from-a-csv-file-containing-headers.asciidoc[]

include::import-data-from-a-csv-file-with-a-custom-field-delimiter.asciidoc[]

include::importing-large-amounts-of-data.asciidoc[]

include::setting-the-rate-of-call-in-transactions.asciidoc[]

include::import-data-containing-escaped-characters.asciidoc[]

include::using-linenumber-with-load-csv.asciidoc[]

//This example was outputting the team city path
//include::using-file-with-load-csv.asciidoc[]

[[load-csv-using-file-with-load-csv]]
== Using file() with LOAD CSV ==
For certain scenarios, like debugging a problem with a csv file, it may be useful to get the absolute path of the file that `LOAD CSV` is operating on.
The `file()` function provides exactly that or `null` if called without a `LOAD CSV` context.

.artists.csv
[source]
----
1,ABBA,1992
2,Roxette,1986
3,Europe,1979
4,The Cardigans,1992
----

.Query
[source, cypher, subs=attributes+]
----
LOAD CSV FROM 'file:///artists.csv' AS line
RETURN DISTINCT file() AS path
----

Since `LOAD CSV` can temporary download a file to process it, it is important to note that `file()` will always return the path on disk.
If `LOAD CSV` is invoked with a `file:///` URL that points to your disk `file()` will return that same path.

.Result
[queryresult]
----
+------------------------------------------+
| path                                     |
+------------------------------------------+
| "/home/example/neo4j/import/artists.csv" |
+------------------------------------------+
1 row
----
