[[query-create-unique]]
= CREATE UNIQUE

[abstract]
The `CREATE UNIQUE` clause is a mix of `MATCH` and `CREATE` -- it will match what it can, and create what is missing.

* <<query-create-unique-introduction, Introduction>>
* <<query-create-unique-nodes, Create unique nodes>>
 ** <<create-unique-create-node-if-missing, Create node if missing>>
 ** <<create-unique-create-nodes-with-values, Create nodes with values>>
 ** <<create-unique-create-labeled-node-if-missing, Create labeled node if missing>>
* <<query-create-unique-relationships, Create unique relationships>>
 ** <<create-unique-create-relationship-if-it-is-missing, Create relationship if it is missing>>
 ** <<create-unique-create-relationship-with-values, Create relationship with values>>
* <<create-unique-describe-complex-pattern, Describe complex pattern>>


[[query-create-unique-introduction]]
== Introduction

[TIP]
`<<query-merge, MERGE>>` might be what you want to use instead of `CREATE UNIQUE`.
Note however, that `MERGE` doesn't give as strong guarantees for relationships being unique.

`CREATE UNIQUE` is in the middle of `MATCH` and `CREATE` -- it will match what it can, and create what is missing.
`CREATE UNIQUE` will always make the least change possible to the graph -- if it can use parts of the existing graph, it will.

Another difference to `MATCH` is that `CREATE UNIQUE` assumes the pattern to be unique.
If multiple matching subgraphs are found an error will be generated.

[TIP]
In the `CREATE UNIQUE` clause, patterns are used a lot.
Read <<cypher-patterns>> for an introduction.

The examples use the following graph:

include::includes/cypher-createunique-graph.asciidoc[]


[[query-create-unique-nodes]]
== Create unique nodes

include::create-node-if-missing.asciidoc[leveloffset=+1]

include::create-nodes-with-values.asciidoc[leveloffset=+1]

include::create-labeled-node-if-missing.asciidoc[leveloffset=+1]


[[query-create-unique-relationships]]
== Create unique relationships

include::create-relationship-if-it-is-missing.asciidoc[leveloffset=+1]

include::create-relationship-with-values.asciidoc[leveloffset=+1]

include::describe-complex-pattern.asciidoc[]

