[[administration-constraints]]
= Constraints

[abstract]
This section explains how to manage constraints used for ensuring data integrity.

* <<administration-constraints-introduction, Introduction>>
* <<administration-constraints-syntax, Syntax>>
* <<administration-constraints-examples, Examples>>
** <<administration-constraints-unique-nodes, Unique node property constraints>>
** <<administration-constraints-prop-exist-nodes, Node property existence constraints>>
** <<administration-constraints-prop-exist-rels, Relationship property existence constraints>>
** <<administration-constraints-node-key, Node key constraints>>
** <<administration-constraints-drop-a-constraint, Drop a constraint>>
** <<administration-constraints-list-constraints, List constraints>>
** <<administration-constraints-deprecated-syntax, Deprecated syntax>>

[[administration-constraints-introduction]]
== Introduction

The following constraint types are available:

*Unique node property constraints*::
Unique property constraints ensure that property values are unique for all nodes with a specific label.
Unique constraints do not mean that all nodes have to have a unique value for the properties -- nodes without the property are not subject to this rule.

*[enterprise-edition]#Node property existence constraints#*::
Node property existence constraints ensure that a property exists for all nodes with a specific label.
Queries that try to create new nodes of the specified label, but without this property, will fail.
The same is true for queries that try to remove the mandatory property.

*[enterprise-edition]#Relationship property existence constraints#*::
Property existence constraints ensure that a property exists for all relationships with a specific type.
All queries that try to create relationships of the specified type, but without this property, will fail.
The same is true for queries that try to remove the mandatory property.

*[enterprise-edition]#Node key constraints#*::
Node key constraints ensure that, for a given label and set of properties:
+
[lowerroman]
. All the properties exist on all the nodes with that label.
. The combination of the property values is unique.

+
Queries attempting to do any of the following will fail:

* Create new nodes without all the properties or where the combination of property values is not unique.
* Remove one of the mandatory properties.
* Update the properties so that the combination of property values is no longer unique.


[NOTE]
Unique node property constraints, node property existence constraints and relationship property existence constraints are only available in Neo4j Enterprise Edition.
Databases containing one of these constraint types cannot be opened using Neo4j Community Edition.

Creating a constraint has the following implications on indexes:

* Adding a unique property constraint on a property will also add a <<administration-indexes-create-a-single-property-index, single-property index>> on that property, so such an index cannot be added separately.
* Adding a node key constraint for a set of properties will also add a <<administration-indexes-create-a-composite-index, composite index>> on those properties, so such an index cannot be added separately.
* Cypher will use these indexes for lookups just like other indexes.
  Refer to <<administration-indexes-search-performance>> for more details on indexes.
* If a unique property constraint is dropped and the single-property index on the property is still required, the index will need to be created explicitly.
* If a node key constraint is dropped and the composite-property index on the properties is still required, the index will need to be created explicitly.

Additionally, the following is true for constraints: 

* A given label can have multiple constraints, and unique and property existence constraints can be combined on the same property.
* Adding constraints is an atomic operation that can take a while -- all existing data has to be scanned before Neo4j can turn the constraint 'on'.
* Best practice is to give the constraint a name when it is created.
If the constraint is not explicitly named, it will get an auto-generated name.
* The constraint name must be unique among both indexes and constraints.
* Constraint creation is not idempotent.
An error will be thrown if you attempt to create the same constraint twice.

[[administration-constraints-syntax]]
== Syntax

.Syntax for managing indexes
[options="header", width="100%", cols="5a,3, 3a"]
|===
| Command | Description | Comment

| [source, cypher, role=noplay]
----
CREATE CONSTRAINT [constraint_name]
ON (n:LabelName) 
ASSERT n.propertyName IS UNIQUE
----
| Create a unique node property constraint.
.4+.^| Best practice is to give the constraint a name when it is created.
If the constraint is not explicitly named, it will get an auto-generated name.

The constraint name must be unique among both indexes and constraints.

Constraint creation is not idempotent.
An error will be thrown if you attempt to create the same constraint twice.
| [source, cypher, role=noplay]]
----
CREATE CONSTRAINT [constraint_name]
ON (n:LabelName) 
ASSERT EXISTS (n.propertyName)
----
| [enterprise-edition]#Create a node property existence constraint.#
| [source, cypher, role=noplay]
----
CREATE CONSTRAINT [constraint_name]
ON ()-"["R:RELATIONSHIP_TYPE"]"-()
ASSERT EXISTS (R.propertyName)
----
| [enterprise-edition]#Create a relationship property existence constraint.#
| [source, cypher, role=noplay]
----
CREATE CONSTRAINT [constraint_name]
ON (n:LabelName) 
ASSERT (n.propertyName_1,
n.propertyName_2,
…
n.propertyName_n)
IS NODE KEY
----
| [enterprise-edition]#Create a node key constraint.#
| [source, cypher, role=noplay]
----
DROP CONSTRAINT constraint_name
----
| Drop a constraint.
| 
| [source, cypher, role=noplay]
----
CALL db.constraints
----
| List all constraints in the database.
|
| [source, cypher, role=noplay]
----
DROP CONSTRAINT
ON (n:LabelName) 
ASSERT n.propertyName IS UNIQUE
----
| Drop a unique constraint without specifying a name.
.4+.^| [deprecated]#This syntax is deprecated.#
| [source, cypher, role=noplay]
----
DROP CONSTRAINT
ON (n:LabelName) 
ASSERT EXISTS (n.propertyName)
----
| Drop an exists constraint without specifying a name.
| [source, cypher, role=noplay]
----
DROP CONSTRAINT
ON ()-"["R:RELATIONSHIP_TYPE"]"-()
ASSERT EXISTS (R.propertyName)
----
| Drop a relationship property existence constraint without specifying a name.
| [source, cypher, role=noplay]
----
DROP CONSTRAINT
ON (n:LabelName) 
ASSERT (n.propertyName_1,
n.propertyName_2,
…
n.propertyName_n)
IS NODE KEY
----
| Drop a node key constraint without specifying a name.
|===

Creating a constraint requires <<administration-security-administration-database-constraints, the `CREATE CONSTRAINT` privilege>>,
while dropping a constraint requires <<administration-security-administration-database-constraints, the `DROP CONSTRAINT` privilege>>.
Listing constraints does not require any privileges.

[[administration-constraints-examples]]
== Examples

[[administration-constraints-unique-nodes]]
=== Unique node property constraints

include::create-a-unique-constraint.asciidoc[leveloffset=+2]

include::create-a-node-that-complies-with-unique-property-constraints.asciidoc[leveloffset=+2]

include::create-a-node-that-violates-a-unique-property-constraint.asciidoc[leveloffset=+2]

include::failure-to-create-a-unique-property-constraint-due-to-conflicting-nodes.asciidoc[leveloffset=+2]




[role=enterprise-edition]
[[administration-constraints-prop-exist-nodes]]
=== Node property existence constraints

include::create-a-node-property-existence-constraint.asciidoc[leveloffset=+2]

include::create-a-node-that-complies-with-property-existence-constraints.asciidoc[leveloffset=+2]

include::create-a-node-that-violates-a-property-existence-constraint.asciidoc[leveloffset=+2]

include::removing-an-existence-constrained-node-property.asciidoc[leveloffset=+2]

include::failure-to-create-a-node-property-existence-constraint-due-to-existing-node.asciidoc[leveloffset=+2]


[role=enterprise-edition]
[[administration-constraints-prop-exist-rels]]
=== Relationship property existence constraints

include::create-a-relationship-property-existence-constraint.asciidoc[leveloffset=+2]

include::create-a-relationship-that-complies-with-property-existence-constraints.asciidoc[leveloffset=+2]

include::create-a-relationship-that-violates-a-property-existence-constraint.asciidoc[leveloffset=+2]

include::removing-an-existence-constrained-relationship-property.asciidoc[leveloffset=+2]

include::failure-to-create-a-relationship-property-existence-constraint-due-to-existing-relationship.asciidoc[leveloffset=+2]


[role=enterprise-edition]
[[administration-constraints-node-key]]
=== Node key constraints

include::create-a-node-key-constraint.asciidoc[leveloffset=+2]

include::create-a-node-that-complies-with-node-key-constraints.asciidoc[leveloffset=+2]

include::create-a-node-that-violates-a-node-key-constraint.asciidoc[leveloffset=+2]

include::removing-a-node-key-constrained-property.asciidoc[leveloffset=+2]

include::failure-to-create-a-node-key-constraint-due-to-existing-node.asciidoc[leveloffset=+2]

//=== Drop a constraint
include::drop-a-constraint.asciidoc[leveloffset=+2]

//=== List constraints
include::list-constraints.asciidoc[leveloffset=+2]


[role=deprecated]
[[administration-constraints-deprecated-syntax]]
=== Deprecated syntax

include::drop-a-unique-constraint.asciidoc[leveloffset=+2]

include::drop-a-node-property-existence-constraint.asciidoc[leveloffset=+2]

include::drop-a-relationship-property-existence-constraint.asciidoc[leveloffset=+2]

include::drop-a-node-key-constraint.asciidoc[leveloffset=+2]
