[[rest-api-cypher]]
== Legacy Cypher HTTP endpoint

:http-api-cypher-uri: {developer-manual-base-uri}/http-api/#http-api-transactional
:cypher-query-lang-uri: {developer-manual-base-uri}/cypher/
:cypher-parameters-uri: {developer-manual-base-uri}/cypher/#cypher-parameters

[NOTE]
--
This endpoint is deprecated.
Please transition to using the transactional HTTP endpoint (see the link:{http-api-cypher-uri}[Developer Manual]).
Among other things it allows you to run multiple Cypher statements in the same transaction.
--

The Neo4j REST API allows querying with Cypher (see the link:{cypher-query-lang-uri}[Cypher documentation]).
The results are returned as a list of string headers (`columns`), and a `data` part, consisting of a list of all rows.
Every row consists of a list of REST representations of the field value -- `Node`, `Relationship`, `Path`, or any simple value like `String`.

[TIP]
--
In order to speed up queries in repeated scenarios, try not to use literals but replace them with parameters wherever possible in order to let the server cache query plans, see <<rest-api-use-parameters>> for details.
Also see the link:{cypher-parameters-uri}[Cypher documentation] for where parameters can be used.
--

include::use-parameters.asciidoc[]

include::create-a-node.asciidoc[]

include::create-a-node-with-multiple-properties.asciidoc[]

include::create-multiple-nodes-with-properties.asciidoc[]

include::set-all-properties-on-a-node-using-cypher.asciidoc[]

include::send-a-query.asciidoc[]

include::return-paths.asciidoc[]

include::nested-results.asciidoc[]

include::retrieve-query-metadata.asciidoc[]

//include::profile-a-query.asciidoc[]

include::errors.asciidoc[]

// not included

//include::array-property.asciidoc[]

//include::nodes-are-represented-as-nodes.asciidoc[]

//include::send-queries-with-errors.asciidoc[]

//include::syntax-errors.asciidoc[]


